name: flutter_app
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  #  pubspec 文件管理着 Flutter 应用程序的静态资源文件(assets)
  #  点击右上角的 Packages get ，将把 package 拉取到项目中
#  为了确保某个包在更新后还可以正常使用，建议使用以下指定版本范围： url_launcher: '>=0.1.2 <0.2.0'
#  flutter_redux 0.5.1
  cupertino_icons: ^0.1.2
  english_words: ^3.1.0
  #  https://pub.dartlang.org/packages/http
  http: ^0.11.3+16
#  这个插件包装了Shared Preferences和NSUserDefaults（与iOS相同）的功能
  shared_preferences: ^0.4.2
  path_provider: "^0.4.1"
  json_annotation: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^0.7.6
  json_serializable: ^0.3.2

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - images/img001.jpg
    - images/img002.jpg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
